### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by FredericaBernkastel** [mserajnik/hydrusrv#9]
In the tags table, you will have 2 columns, first will contain lowercase version of tag (used in queries), second - original tag (will be displayed).

If there are same tags but with different casing, they will be handled as siblings in future.

**Comment by mserajnik** [comment]
Example:

- You have two tags: `Lorem` and `lorem`. Lower cased they are both `lorem`
- Searching for `lorem` in the files view would now display all files that have either tag
- Searching for `lorem` in the tags view would display both tags. Clicking on one of them would then run a search for files having either tag, because we are always comparing with the lowercased version (otherwise we‘d need an additional route/parameter to search case sensitive as well)
- In addition, searching for `lOrEm` will lowercase the search string and compare with the lowercased version

Correct?
- Searching

**Comment by FredericaBernkastel** [comment]
Correct.
Also, count of files per tag, will now display sum of all alternates.

**Comment by mserajnik** [comment]
But in that case I‘d suggest only display either one of those tags in the tags listing/autocomplete (maybe just the one that‘s selected first when querying). Because otherwise we‘d show the same count on all of them. Don‘t you think that‘s a bit confusing?

(I‘ll let you decide here because I personally don‘t have this use case, I only have lowercase tags and none are the same)

**Comment by FredericaBernkastel** [comment]
In both tags listing/autocomplete, if tag has no alternates, display it in orginal case. Otherwise, show only one of alternates, in lower casing.

**Comment by FredericaBernkastel** [comment]
This does not affect namespaces.
Namespaces with alternate casing will stay handled as unique.

**Comment by mserajnik** [comment]
Actually, I think this is a non-issue.

hydrus itself doesn't seem to differentiate between casing. Try adding a tag uppercase or with mixed casing – it will always assign the tag lowercase.

Unless case-insensitivity is an option in hydrus I'm not aware of or was a thing in an older version.

**Comment by FredericaBernkastel** [comment]
> hydrus itself doesn't seem to differentiate between casing. Try adding a tag uppercase or with mixed casing – it will always assign the tag lowercase.

Just noticed :joy:
So we can simply convert input to lower.

**Comment by mserajnik** [comment]
Will do. :D

**Comment by mserajnik** [comment]
Actually, this already happens, but wrongly: it displays the set tag lowrcase but will still make the query in the casing used. Will fix that.

**Comment by mserajnik** [comment]
Will be fixed in https://github.com/mserajnik/hydrusrvue/commit/e6e99b935036d3815df465e62888adbb3bdb00d4. All tags in the frontend are now made lowercase before the queries are sent.

I've also noticed that on `LIKE` comparisons (used in tags search and autocomplete), `_` is a wildcard for any single character. This means that `purple eyes` and `purple_eyes` will both work when compared to `purple eyes`. I've fixed this by escaping `_` in https://github.com/mserajnik/hydrusrv/commit/47fa6e6949eb3a321da6d4d77e0fa5be338d9a03 so that `_` can actually be used as a regular character.

**Comment by mserajnik** [comment]
Fixed: https://github.com/mserajnik/hydrusrv/tree/3.16.0.

**Comment by FredericaBernkastel** [comment]
You forgot about input on home page. It doesn't convert case.

**Comment by mserajnik** [comment]
Good catch, thanks.
